# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APIExample' do
  use_frameworks!
  pod 'Floaty', '~> 4.2.0'  
  pod 'AGEVideoLayout', '~> 1.0.2'
  pod 'CocoaAsyncSocket', '7.6.5'
#  pod 'AgoraNGSDK', :path => 'sdk'
end


target 'SimpleFilter' do
#  pod 'AgoraNGSDK', :path => 'sdk'
  pod 'OpenCV2', '~> 4.3.0'
  use_frameworks!

end
